### ISSUE TITLE
[Bug]: Chunks just cease to load in versions 1.5.0 and 1.5.1

### ISSUE THREAD

**Issue by CodeBot101** [someaddons/betterchunkloading#36]
### Describe the bug you're experiencing

Updating to 1.5.0/1.5.1 from 1.4.5 resulted in smoother loaded chunks, buuuut the chunks rather quickly grind to a halt and either NEVER start loading again (in ANY direction), or sometimes if I backtrack, the previous chunks will load, which will prompt the stuck chunks to start loading again when I go back

**Importantly:**
- The TPS is not freezing; it's going perfectly fine, and it's healthy, too. However, I can't interact with or break blocks while the chunk-loading stall is happening, but other mobs are still moving around, getting hurt, updating, etc., so I have no clue what's going on, and only know that something about the new version of betterchunkloading causes this with the same mod list I had before
- The FPS is not freezing either.

Chunks load perfectly in 1.4.5 but not in 1.5.0/1.5.1 with the SAME exact mods:

[Mod list](https://pastebin.com/eJEULHBn)

### Reproducability

Have my modlist and load up a world with version 1.5.0 or 1.5.1 of this mod, apparently.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/CodeBot101/4fe49beef1a857815d32b43f09b51c35

**Comment by CodeBot101** [comment]
Also, the chunks don't seem to be predicting my movement to load; they're just all loading in a wide area like vanilla MC

**Comment by someaddons** [comment]
Can you export/upload your modpack please? Can't reproduce it it without and not going to install 270 mods by hand :D

**Comment by CodeBot101** [comment]
Oh yeah, that would've been helpful i suppose lol

This might have the old 1.4.5 version of ur mod in it, but just change it to 1.5.0 or 1.5.1 and it should break perfectly! :D
https://drive.google.com/file/d/1BZAY9Rq5pp-pe8j1EomHWgob0lVCTDZw/view?usp=sharing <-- My modpack v18

To reproduce the stall quickly, just pick a direction and fly in it for a few minutes.

If that version somehow doesn't break, try it with this newer version; you will **definitely** have to manually change ur mod to 1.5.0/1.5.1 in this version though
https://drive.google.com/file/d/17JOq4KgBorWejms7X-kZGpaCFodlcke1/view?usp=sharing <-- My modpack v18.2

**Comment by someaddons** [comment]
Fixed in 5.2, was a side effect of the prevent players walking into unloaded chunks, when you had slow chunk generation and kept walking further

**Comment by CodeBot101** [comment]
Tested with about ~1 hour of play or so, and it seems fixed!

I still don't fully understand what the specific issue was, but you're smart af and you fixed it, so I'd consider this done and dusted

Thanks!
